export const mockCostData = {
  totalCost: 47832.56,
  previousMonthCost: 42150.30,
  dailyCosts: [
    { date: "Mar 1", aws: 1250, gcp: 890, total: 2140 },
    { date: "Mar 2", aws: 1180, gcp: 920, total: 2100 },
    { date: "Mar 3", aws: 1320, gcp: 870, total: 2190 },
    { date: "Mar 4", aws: 1400, gcp: 910, total: 2310 },
    { date: "Mar 5", aws: 1290, gcp: 880, total: 2170 },
    { date: "Mar 6", aws: 3850, gcp: 920, total: 4770 },
    { date: "Mar 7", aws: 1350, gcp: 890, total: 2240 },
    { date: "Mar 8", aws: 1280, gcp: 940, total: 2220 },
    { date: "Mar 9", aws: 1310, gcp: 870, total: 2180 },
    { date: "Mar 10", aws: 1420, gcp: 900, total: 2320 },
    { date: "Mar 11", aws: 1190, gcp: 850, total: 2040 },
    { date: "Mar 12", aws: 1360, gcp: 910, total: 2270 },
    { date: "Mar 13", aws: 1280, gcp: 880, total: 2160 },
    { date: "Mar 14", aws: 4200, gcp: 3100, total: 7300 },
  ],
  serviceBreakdown: [
    { name: "EC2 / Compute", cost: 18500, percentage: 38.7 },
    { name: "S3 / Storage", cost: 8200, percentage: 17.1 },
    { name: "Lambda / Functions", cost: 5600, percentage: 11.7 },
    { name: "RDS / Database", cost: 7800, percentage: 16.3 },
    { name: "CloudFront / CDN", cost: 3200, percentage: 6.7 },
    { name: "Other", cost: 4532, percentage: 9.5 },
  ],
};

export const mockAlerts = [
  {
    id: "1",
    severity: "high" as const,
    title: "Unusual EC2 spending spike detected",
    description: "EC2 costs increased by 205% on Mar 6, deviating significantly from the 7-day average.",
    service: "AWS EC2",
    amount: 3850,
    expected: 1260,
    timestamp: "2026-03-06T14:23:00Z",
    status: "active" as const,
  },
  {
    id: "2",
    severity: "high" as const,
    title: "Multi-service cost anomaly",
    description: "Both AWS and GCP costs spiked simultaneously on Mar 14, indicating potential misconfiguration.",
    service: "Multiple",
    amount: 7300,
    expected: 2200,
    timestamp: "2026-03-14T09:15:00Z",
    status: "active" as const,
  },
  {
    id: "3",
    severity: "medium" as const,
    title: "S3 storage costs trending upward",
    description: "S3 storage costs have increased 15% week-over-week for the past 3 weeks.",
    service: "AWS S3",
    amount: 8200,
    expected: 7100,
    timestamp: "2026-03-12T11:00:00Z",
    status: "active" as const,
  },
  {
    id: "4",
    severity: "low" as const,
    title: "Lambda invocation cost increase",
    description: "Lambda costs are 8% above the monthly forecast.",
    service: "AWS Lambda",
    amount: 5600,
    expected: 5180,
    timestamp: "2026-03-10T16:45:00Z",
    status: "resolved" as const,
  },
];

export const mockRecommendations = [
  {
    id: "1",
    category: "compute",
    title: "Stop 4 idle EC2 instances",
    description: "Instances i-0a1b2c, i-3d4e5f, i-6g7h8i, i-9j0k1l have been idle (< 5% CPU) for 7+ days.",
    potentialSavings: 1240,
    impact: "high" as const,
    provider: "AWS",
  },
  {
    id: "2",
    category: "storage",
    title: "Delete 2.3TB of unused S3 objects",
    description: "Objects in buckets 'backup-archive' and 'temp-uploads' haven't been accessed in 90+ days.",
    potentialSavings: 680,
    impact: "medium" as const,
    provider: "AWS",
  },
  {
    id: "3",
    category: "compute",
    title: "Right-size 6 over-provisioned VMs",
    description: "6 Compute Engine instances are running at < 20% CPU utilization. Consider downsizing.",
    potentialSavings: 890,
    impact: "high" as const,
    provider: "GCP",
  },
  {
    id: "4",
    category: "scheduling",
    title: "Schedule dev environment shutdown",
    description: "Development instances run 24/7 but are only accessed during business hours (9AM-6PM).",
    potentialSavings: 1560,
    impact: "high" as const,
    provider: "AWS",
  },
  {
    id: "5",
    category: "storage",
    title: "Enable lifecycle policies on GCS buckets",
    description: "3 Cloud Storage buckets lack lifecycle policies. Moving old objects to Nearline could save costs.",
    potentialSavings: 340,
    impact: "low" as const,
    provider: "GCP",
  },
];

export const mockCloudAccounts = [
  {
    id: "1",
    provider: "AWS" as const,
    name: "Production Account",
    accountId: "123456789012",
    status: "connected" as const,
    lastSync: "2026-03-07T08:00:00Z",
    monthlyCost: 32500,
  },
  {
    id: "2",
    provider: "GCP" as const,
    name: "GCP Project Alpha",
    accountId: "project-alpha-382910",
    status: "connected" as const,
    lastSync: "2026-03-07T07:45:00Z",
    monthlyCost: 15332,
  },
];

export const mockAnomalies = [
  { date: "Mar 6", service: "EC2", actual: 3850, expected: 1260, score: 0.92, status: "anomaly" as const },
  { date: "Mar 14", service: "Multi", actual: 7300, expected: 2200, score: 0.97, status: "anomaly" as const },
  { date: "Mar 3", service: "S3", actual: 870, expected: 750, score: 0.45, status: "normal" as const },
  { date: "Mar 9", service: "Lambda", actual: 1310, expected: 1200, score: 0.38, status: "normal" as const },
  { date: "Mar 11", service: "RDS", actual: 1190, expected: 1180, score: 0.12, status: "normal" as const },
];

export const mockUsers = [
  { id: "1", name: "John Admin", email: "john@company.com", role: "admin" as const, lastLogin: "2026-03-07T08:00:00Z", status: "active" as const },
  { id: "2", name: "Sarah Ops", email: "sarah@company.com", role: "user" as const, lastLogin: "2026-03-06T14:30:00Z", status: "active" as const },
  { id: "3", name: "Mike Dev", email: "mike@company.com", role: "user" as const, lastLogin: "2026-03-05T09:15:00Z", status: "active" as const },
  { id: "4", name: "Lisa Finance", email: "lisa@company.com", role: "user" as const, lastLogin: "2026-02-28T11:00:00Z", status: "inactive" as const },
];
